# Generated by Django 4.1.1 on 2023-01-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, verbose_name='book_title')),
                ('issue_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
            ],
        ),
    ]
